# Default values for kubernetes-dbaas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Repository of the operator manager image.
  repository:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Allocating less resources might create problems
resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

# The termination grace period of your operator manager container.
terminationGracePeriodSeconds: 10

# Overrides the ServiceAccount subject to receive the access rights needed to run the manager Pod correctly. Look at
# role.yaml and role_binding.yaml to find out more.
serviceAccountName: controller-manager

# Should the ServiceAccount of the manager Pod automount the SA Account Token?
# otherwise
automountServiceAccountToken: true

# Path of the operator configuration which will be mounted in the manager Pod
operatorConfigPath: "/var/kubedbaas"

# Operator configuration. The first key is the name of Secret file mounted in the manager Pod. Consult the System administrator guide to learn more.
operatorConfig:
  config.yaml: |
    dbms:
      - driver: sqlserver
        endpoints:
          - name: us-sqlserver-test
            dsn: sqlserver://sa:Password&1@localhost
        operations:
          create:
            name: sp_create
            inputs:
              k8sName: k8sName
            outputs:
              password: password
              username: username
          delete:
            name: sp_delete
            inputs:
              k8sName: k8sName
