# config.yaml
---
dbms:
  - driver: sqlserver
    endpoints:
      - name: us-sqlserver-test
        dsn: "sqlserver://sa:Password&1@localhost"
    operations:
      create:
        name: "sp_create"
        inputs:
          k8sName: k8sName
        outputs:
          password: password
          username: username
      delete:
        name: "sp_delete"
        inputs:
          k8sName: k8sName
