apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: widmaster/kubernetes-dbaas # must match in artifactOverrides
deploy:
  helm:
    releases:
    - name: kubernetes-dbaas
      namespace: kubernetes-dbaas
      chartPath: charts/kubernetes-dbaas
      valuesFiles:
        - charts/kubernetes-dbaas/values_sensible.yaml
      artifactOverrides:
        image: widmaster/kubernetes-dbaas # no tag present!
      imageStrategy:
        helm: {}


