# permissions for end users to view databaseclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseclass-viewer-role
rules:
- apiGroups:
  - databaseclass.dbaas.bedag.ch
  resources:
  - databaseclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databaseclass.dbaas.bedag.ch
  resources:
  - databaseclasses/status
  verbs:
  - get
