# permissions for end users to edit databaseclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databaseclass-editor-role
rules:
- apiGroups:
  - databaseclass.dbaas.bedag.ch
  resources:
  - databaseclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databaseclass.dbaas.bedag.ch
  resources:
  - databaseclasses/status
  verbs:
  - get
