# permissions for end users to edit database.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-editor-role
rules:
- apiGroups:
  - dbaas.bedag.ch
  resources:
  - database
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.bedag.ch
  resources:
  - database/status
  verbs:
  - get
