# permissions for end users to view database.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-viewer-role
rules:
- apiGroups:
  - dbaas.bedag.ch
  resources:
  - database
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.bedag.ch
  resources:
  - database/status
  verbs:
  - get
