# permissions for end users to view kubernetesdbaas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesdbaas-viewer-role
rules:
- apiGroups:
  - dbaas.bedag.ch
  resources:
  - kubernetesdbaas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.bedag.ch
  resources:
  - kubernetesdbaas/status
  verbs:
  - get
