apiVersion: v2
description: A Helm chart for the Kubernetes-DbaaS operator. See https://github.com/bedag/kubernetes-dbaas.
name: kubernetes-dbaas
version: 0.2.0
appVersion: 0.2.0
kubeVersion: ">= 1.21.0"
type: application
keywords:
  - "kubernetes-dbaas"
  - "operator"
  - "database-as-a-service"
  - "dbaas"
  - "stored procedures"
  - "kubernetes operator"
icon: icon.png
home: https://github.com/bedag/kubernetes-dbaas
sources:
  - https://github.com/bedag/kubernetes-dbaas
maintainers:
  - name: "criscola"
    email: "cristiano.colangelo@bluewin.ch"
    url: "https://github.com/criscola"
