# Default values for kubernetes-dbaas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Repository of the operator manager image.
  repository: criscola/kubernetes-dbaas
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# Allocating less resources might create problems
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

# The termination grace period of your operator manager container.
terminationGracePeriodSeconds: 10

# Manager service account name
managerSaName: kubernetes-dbaas-controller-manager

# Should the ServiceAccount of the manager Pod automount the SA Account Token?
# otherwise
automountServiceAccountToken: true

managerArgs: ["--debug=true"]

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

prometheusSaName: prometheus-kube-prometheus-prometheus

prometheusSaNamespace: default

# Operator configuration. The first key is the name of Secret file mounted in the manager Pod. Consult the System administrator guide to learn more.
operatorConfig:
  health:
    healthProbeBindAddress: :8081
  metrics:
    bindAddress: 127.0.0.1:8080
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceName: bfa62c96.dbaas.bedag.ch
  rps: 1
  dbms:
    - databaseClassName: "databaseclass-sample-sqlserver"
      endpoints:
        - name: "us-sqlserver-test"
          dsn: "sqlserver://sa:Password&1@192.168.49.1:1433"
    - databaseClassName: "databaseclass-sample-psql"
      endpoints:
        - name: "us-postgres-test"
          dsn: "psql://postgres:Password&1@192.168.49.1:5432"