replicaCount: 1

image:
  # Repository of the operator manager image.
  repository: criscola/kubernetes-dbaas
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# Allocating less resources might create problems
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

# The termination grace period of your operator manager container.
terminationGracePeriodSeconds: 10

# Manager service account name
managerSaName: kubernetes-dbaas-controller-manager

# Should the ServiceAccount of the manager Pod automount the SA Account Token?
# otherwise
automountServiceAccountToken: true

managerArgs: ["--debug=true"]

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

# You can supply your values for the kube-prometheus-stack chart here, or just disable it.
# If you disabled metrics, the kube-prometheus-stack dependency requirement will be disabled as well.
# You can also just deploy a Prometheus instance, granted that it watches for ServiceMonitor resources in order to
# scrape metrics.
kubePrometheusStack:
  enabled: true
  # Service account name authorized to access the metrics endpoint.
  prometheusSaName: prometheus-kube-prometheus-prometheus
  # Service account namespace authorized to access the metrics endpoint.
  prometheusSaNamespace: default
  # Namespace of Prometheus to be rendered in the relative Service Monitor resource
  namespaceOverride: prometheus
# You can supply your value for the cert-manager chart here, or just disable it.
# If you disabled metrics, the cert-manager dependency requirement will be disabled as well.
certmanager:
  enabled: true

# Disables the metrics endpoint. Setting this value to true will set (override) operatorConfig.metrics.bindAddress to "0" and
# disable the kube-prometheus-stack and cert-manager dependency requirements.
enableMetrics: true

# Operator configuration including the relative Manager configuration.
# See https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.3/pkg/config/v1alpha1#ControllerManagerConfigurationSpec.
operatorConfig:
  health:
    healthProbeBindAddress: :8081
  metrics:
    bindAddress: 127.0.0.1:8080
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceName: bfa62c96.dbaas.bedag.ch
  # Specifies the maximum number of operations per second allowed per endpoint. Set to 0 to disable rate limiting.
  rps: 1
  # Describes the DBMS configuration. Each entry includes a "databaseClassName" attribute specifying
  # the name of the DatabaseClass resource associated with the endpoints along with an "endpoints" attribute
  # specifying the "name" of endpoint to be made available to end-users as well as its connection string (DSN).
  # To learn more about the supported DSN formats, see: https://github.com/xo/dburl.
  dbms:
    - databaseClassName: "databaseclass-sample-sqlserver"
      endpoints:
        - name: "us-sqlserver-test"
          dsn: "sqlserver://sa:Password&1@192.168.58.1:1433"
    - databaseClassName: "databaseclass-sample-psql"
      endpoints:
        - name: "us-postgres-test"
          dsn: "postgres://postgres:Password&1@192.168.58.1:5432/postgres"
    - databaseClassName: "databaseclass-sample-mariadb"
      endpoints:
        - name: "us-mariadb-test"
          dsn: "mariadb://root:Password&1@192.168.58.1:3306/mysql"