apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-dbaas-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kubernetes-dbaas.labels" . | nindent 4 }}
spec:
  dnsNames:
    - kubernetes-dbaas-webhook-service.{{ .Release.Namespace }}.svc
    - kubernetes-dbaas-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kubernetes-dbaas-selfsigned-issuer
  secretName: webhook-server-cert