apiVersion: databaseclass.dbaas.bedag.ch/v1
kind: DatabaseClass
metadata:
  name: databaseclass-sample-psql
spec:
  driver: "postgres"
  operations:
    create:
      name: "create"
    delete:
      name: "delete"
    rotate:
      name: "rotate"
  secretFormat:
    username: "{ { .Result.username }}"
    password: "{ { .Result.password }}"
    port: "{ { .Result.port }}"
    dbName: "{ { .Result.dbName }}"
    server: "{ { .Result.fqdn }}"
    lastRotation: "{ { .Result.lastRotation }}"
    dsn: "psql://{ { .Result.username }}:{ { .Result.password }}@{ { .Result.fqdn }}:{ { .Result.port }}/{ { .Result.dbName }}"