apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-dbaas.fullname" . }}
  labels:
    {{- include "kubernetes-dbaas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubernetes-dbaas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubernetes-dbaas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: operator-config
              mountPath: {{ .Values.operatorConfigPath | default "/var/kubedbaas" }}
              readOnly: true
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          command:
            - /manager
          {{- if .Values.operatorConfigPath }}
          args:
            - "--load-config"
            - {{ print .Values.operatorConfigPath "/config.yaml"  | quote }}
          {{- end }}
      volumes:
        - name: operator-config
          secret:
            secretName: controller-manager
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
