apiVersion: v1
data:
  controller_manager_config.yaml: |-
    apiVersion: config.dbaas.bedag.ch/v1
    kind: OperatorConfig
    {{ .Values.operatorConfig | toYaml | indent 4 | trim }}
kind: ConfigMap
metadata:
  name: kubernetes-dbaas-manager-config
  namespace: {{ .Release.Namespace }}