
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubernetes-dbaas-manager-role
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kubernetes-dbaas.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - list
      - update
      - watch
  - apiGroups:
      - database.dbaas.bedag.ch
    resources:
      - databases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.dbaas.bedag.ch
    resources:
      - databases/finalizers
    verbs:
      - update
  - apiGroups:
      - database.dbaas.bedag.ch
    resources:
      - databases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - databaseclass.dbaas.bedag.ch
    resources:
      - databaseclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch