apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dbaas-metrics-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-dbaas-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheusSaName }}
    namespace: {{ .Values.prometheusSaNamespace }}