{{ if .Values.enableMetricsRbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-dbaas-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{ end }}