apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kubernetes-dbaas-serving-cert
  creationTimestamp: null
  name: kubernetes-dbaas-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: kubernetes-dbaas-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-database-dbaas-bedag-ch-v1-database
    failurePolicy: Fail
    name: mdatabase.kb.io
    rules:
      - apiGroups:
          - database.dbaas.bedag.ch
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - databases
    sideEffects: None