apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dbaas-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-dbaas-proxy-role
subjects:
  - kind: ServiceAccount
    name:  {{ .Values.managerSaName }}
    namespace: {{ .Release.Namespace }}