apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - dbaas.bedag.ch
    resources:
      - databases
    verbs:
      - list
      - watch
      - update
  - apiGroups:
      - dbaas.bedag.ch
    resources:
      - databases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - dbaas.bedag.ch
    resources:
      - databaseclasses
    verbs:
      - get
      - list
      - create
      - delete
      - update
      - watch

  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - list
    - create
    - delete
    - update
    - watch
