apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.operatorConfigFilename | default "config.yaml" }}: {{ toYaml .Values.operatorConfig | b64enc | quote }}