name: Helm Chart linter

on:
  pull_request:
    branches: [main]
    paths: [ 'charts/kubernetes-dbaas/**', '.github/workflows/helm.yaml' ]
  push:
    branches: [main]
    paths: [ 'charts/kubernetes-dbaas/**', '.github/workflows/helm.yaml' ]

jobs:
  checks:
    name: Helm Chart linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --all